---
## Kibana Configuration
server.name: kibana
server.host: 0.0.0.0
server.port: 5601

# Monitoring
monitoring.ui.enabled: true

# Disable telemetry
telemetry.enabled: false
telemetry.optIn: false

# Session settings
xpack.security.session.idleTimeout: "1h"
xpack.security.session.lifespan: "8h"

# Logging
logging.root.level: info
